version: "3.8"

services:
  books-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: books_api
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
