name: Deploy NestJS to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "."
          target: "~/nestjs-app"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.EC2_USERNAME }}
         key: ${{ secrets.EC2_PRIVATE_KEY }}
         script: |
           sudo apt-get update
           sudo apt-get install -y docker.io
           sudo curl -SL https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64 \
           -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose

           cd ~/nestjs-app
           docker-compose down || true
           docker-compose up -d --build
